title: ♬ (Git)ting to know you, getting to know all about Git! ♬
email: mike.dillion@gmail.com
description: >
  This event will consist of a presentation and workshop geared towards those who
  want to be effective using Git and Github to collaborate on community projects.
  No programming skills required! The topics discussed will apply to many use
  cases such as: organizing projects, collaborating on documents, and just boring
  old code stuff.

  After a presentation covering core concepts, participants will use their choice
  of tools (command-line, GUI, or just Github) to practice basic work-flows that
  are used to contribute to projects.
baseurl: "http://gitting_to_know_you.mikedillion.com"
url: "http://gitting_to_know_you.mikedillion.com"
twitter_username: mikedillion
github_username: mikedillion

markdown: kramdown
exclude: [Gemfile, Gemfile.lock]
